import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    POSTGRES_USER = os.environ['POSTGRES_USER']
    POSTGRES_PASSWORD = os.environ['POSTGRES_PASSWORD']
    POSTGRES_DEFAULT_DB = os.environ['POSTGRES_DEFAULT_DB']
    POSTGRES_HOST = os.environ['POSTGRES_HOST']
    POSTGRES_PORT = os.environ['POSTGRES_PORT']

    # RAG
    AZURE_SEARCH_SERVICE_ENDPOINT = os.environ['AZURE_SEARCH_SERVICE_ENDPOINT']
    AZURE_SEARCH_API_KEY = os.environ['AZURE_SEARCH_API_KEY']
    AZURE_SEARCH_SEMANTIC_CONFIGURATION_NAME = os.environ['AZURE_SEARCH_SEMANTIC_CONFIGURATION_NAME']

    OPENAI_EMBEDDING_MODEL = os.environ['OPENAI_EMBEDDING_MODEL']

    RAG_CHUNK_SIZE = int(os.environ['RAG_CHUNK_SIZE'])
    RAG_CHUNK_OVERLAP = int(os.environ['RAG_CHUNK_OVERLAP'])

    TOP_K = int(os.environ['TOP_K'])
    RAG_SYSTEM_PROMPT = os.environ['RAG_SYSTEM_PROMPT']

    # Azure Blob Storage
    AZURE_BLOB_STORAGE_CONN_STR = os.environ['AZURE_BLOB_STORAGE_CONN_STR']
    AZURE_BLOB_STORAGE_BASE_URL = os.environ['AZURE_BLOB_STORAGE_BASE_URL']

    # MongoDB
    MONGO_DB_URI = os.environ['MONGO_DB_URI']
    MONGO_DB_DATABASE = os.environ['MONGO_DB_DATABASE']
    MONGO_FILE_COLLECTION = os.environ['MONGO_FILE_COLLECTION']
    MONGO_META_COLLECTION = os.environ['MONGO_META_COLLECTION']
    MONGO_CHAT_COLLECTION = os.environ['MONGO_CHAT_COLLECTION']

    #TENCAITY
    RETRY_ATTEMPTS = os.environ['RETRY_ATTEMPTS']
    RETRY_MULTIPLIER = os.environ['RETRY_MULTIPLIER']
    RETRY_MIN = os.environ['RETRY_MIN']
    RETRY_MAX = os.environ['RETRY_MAX']